attributeList={
#Table=student
#key value
'customerid':['customers.customer_Id'],
'customer':['customers.customer_Id'],
'cif':['customers.customer_Id'],
'cid':['customers.customer_Id'],
'cno':['customers.customer_Id'],
'DOB':['customers.DOB'],
'dob':['customers.DOB'],
'gender':['customers.Gender'],
'sex':['customers.Gender'],
'categorycode': ['products.prod_cat_code'],
'productcode': ['products.prod_cat_code'],
'catcode': ['products.prod_cat_code'],
'product category': ['products.prod_cat'],
'product cat': ['products.prod_cat'],
'category':['products.prod_cat'],
'sub cat':['products.prod_subcat'],
'subcategory':['products.prod_subcat'],
'tid':['transactions.transaction_id'],
'customerid':['transactions.cust_id'],
'cid':['transactions.cust_id'],
'cno':['transactions.cust_id'],
'tran_date':['transactions.tran_date'],
'transaction date':['transcations.tran_date'],
'subcat':['transactions.prod_sub_cat_code'],
'subcategory code':['transaction.prod_sub_cat_code'],
'productsubcat':['transactions.prod_subcat'],
'subcatcode':['transactions.prod_subcat'],
'subcategory':['transcation.prod_subcat'],
'qty':['transactions.Qty'],
'quantity':['transactions.Qty'],
'quantities':['transactions.Qty'],
'number':['transactions.Qty'],
'rate':['transactions.Rate'],
'price':['transactions.Rate'],
'cost':['transactions.Rate'],
'amount':['transactions.Rate'],
'mrp':['transactions.Rate'],
'tax':['transactions.tax'],
'tamount':['transactions.total_amt'],
'netamount':['transactions.total_amt'],
'netamt':['transactions.total_amt'],
'tprice':['transactions.total_amt'],
'tcost':['transactions.total_amt'],
'totalsales':['transactions.total_amt'],
'sales':['transactions.total_amt'],
'netprice':['transactions.total_amt'],
'Storetype':['transactions.Store_type'],
'mode':['transactions.Store_type'],
'shopmode':['transactions.Store_type'],
'product':['products.prod_cat']
}
